export const products = [
  {
    id: 1,
    name: "سمك السلمون النرويجي",
    description: "سمك سلمون طازج من النرويج، غني بأوميغا 3 ومثالي للشوي والتدخين",
    price: 89.99,
    oldPrice: 109.99,
    unit: "كيلوغرام",
    category: "أسماك فاخرة",
    image: "/placeholder.svg?height=600&width=600",
    badge: "خصم",
    rating: 5,
    reviews: 124,
  },
  {
    id: 2,
    name: "سمك الهامور الطازج",
    description: "هامور طازج من الخليج العربي، لحم أبيض طري ومثالي للطبخ بمختلف الطرق",
    price: 95.5,
    unit: "كيلوغرام",
    category: "أسماك محلية",
    image: "/placeholder.svg?height=600&width=600",
    badge: "الأكثر مبيعًا",
    rating: 4,
    reviews: 89,
  },
  {
    id: 3,
    name: "روبيان خليجي جامبو",
    description: "روبيان خليجي كبير الحجم ومنظف، مثالي للشوي والقلي والطبخ",
    price: 135.75,
    unit: "كيلوغرام",
    category: "قشريات",
    image: "/placeholder.svg?height=600&width=600",
    badge: "جديد",
    rating: 5,
    reviews: 56,
  },
  {
    id: 4,
    name: "سمك السيباس المتوسطي",
    description: "سمك سيباس طازج من البحر المتوسط، منظف وجاهز للطهي",
    price: 78.25,
    oldPrice: 92.0,
    unit: "كيلوغرام",
    category: "أسماك فاخرة",
    image: "/placeholder.svg?height=600&width=600",
    badge: "خصم",
    rating: 4,
    reviews: 42,
  },
  {
    id: 5,
    name: "سمك التونة الطازج",
    description: "تونة طازجة عالية الجودة، غنية بالبروتين ومثالية للسلطات والساشيمي",
    price: 120.5,
    unit: "كيلوغرام",
    category: "أسماك فاخرة",
    image: "/placeholder.svg?height=600&width=600",
    badge: "جديد",
    rating: 5,
    reviews: 78,
  },
  {
    id: 6,
    name: "محار طازج",
    description: "محار طازج من أفضل المصادر، مثالي للتقديم النيء أو المطبوخ",
    price: 150.0,
    unit: "دزينة",
    category: "محاريات",
    image: "/placeholder.svg?height=600&width=600",
    badge: "فاخر",
    rating: 4,
    reviews: 35,
  },
  {
    id: 7,
    name: "سمك الكنعد الطازج",
    description: "سمك كنعد طازج من الخليج العربي، مثالي للشوي والقلي",
    price: 85.75,
    unit: "كيلوغرام",
    category: "أسماك محلية",
    image: "/placeholder.svg?height=600&width=600",
    badge: "الأكثر مبيعًا",
    rating: 4,
    reviews: 62,
  },
  {
    id: 8,
    name: "كاليماري طازج",
    description: "كاليماري (حبار) طازج ومنظف، جاهز للطهي بمختلف الطرق",
    price: 95.25,
    unit: "كيلوغرام",
    category: "قشريات",
    image: "/placeholder.svg?height=600&width=600",
    badge: "طازج",
    rating: 4,
    reviews: 48,
  },
]
